export const metadata = {
    title: 'About - SeonDrive',
    // description: 'Generated by Next.js',
  }

const about = () => {
  return (
    <div>Page about à venir</div>
  )
}
export default about