export const metadata = {
    title: 'Contacts - SeonDrive',
    // description: 'Generated by Next.js',
  }
  
  const contacts = () => {
  return (
    <div>contacts</div>
  )
}
export default contacts