export const metadata = {
    title: 'Vehicules - SeonDrive',
    // description: 'Generated by Next.js',
  }

const vehicules = () => {
  return (
    <div>vehicules</div>
  )
}
export default vehicules